[package]
name = "parser"
version = "0.1.0"
authors = ["Vlad Grigorescu <vlad@es.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cbindgen = "0.14.3"

[lib]
crate-type = ["cdylib"]