[package]
name = "parser"
version = "0.1.0"
authors = ["Vlad Grigorescu <vlad@es.net>"]
edition = "2018"

[dependencies]
libc = "0.2.74"
nom = "5.1.2"

[build-dependencies]
cbindgen = "0.14.3"

[lib]
crate-type = ["cdylib"]